### ISSUE TITLE
Falha para funcionar no QGIS "Pi"

### ISSUE THREAD

**Issue by Jbfjr** [lmotta/mapbiomasalert#1]
Tenho encontrado a seguinte falha quando tento rodar ou no QGIS 3.10 ou no "Pi":

![falha](https://user-images.githubusercontent.com/69658622/90202378-eb9c6080-ddb3-11ea-8202-42a6e4c7e2ca.JPG)

**Comment by lmotta** [comment]
Houve uma alteração no serviço do MapBiomas Alerta.
Assim que me passarem as alterações irei atualizar o Plugin.
Obrigado por registrar.

Em qui., 13 de ago. de 2020 às 22:26, Jbfjr <notifications@github.com>
escreveu:

**Comment by lmotta** [comment]
Favor atualizar o plugin(1.2)
