### ISSUE TITLE
Impossível carregar complemento 'mapbiomasalert' 

### ISSUE THREAD

**Issue by gourmandrs** [lmotta/mapbiomasalert#2]
Após atualização o complemento deixou de funcionar. Uso Ubuntu 20.04 e Qgis 3.10.4. Por favor, podem me ajudar a solucionar isto?

Impossível carregar complemento 'mapbiomasalert' 

ModuleNotFoundError: No module named 'planet_explorer' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/miura/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapbiomasalert/__init__.py", line 29, in 
    from planet_explorer.extlibs.planet import api
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'planet_explorer'

Versão do Python: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0] 
Versão do QGIS: 3.10.4-A Coruña A Coruña, exported 

Caminho do Python:
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python/plugins/clusterpoints
/usr/share/qgis/python
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgisQueryBuilder
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python/plugins/postgisQueryBuilder/extlibs
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python/plugins/inde
/home/miura/.local/share/QGIS/QGIS3/profiles/default/python/plugins/kmltools/libs

**Comment by lmotta** [comment]
Thanks.
Fixed, please update plugin(1.2)
